# Generated by Django 3.1.7 on 2021-12-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_funcionario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='user',
            new_name='usuario',
        ),
    ]
